version: '3'

services:
  db:
    image: mysql:5.7  
    restart: always    
    volumes: 
       - ./db_data:/var/lib/mysql  
    env_file: 
      - ./env/mysql.development.env

  web:   
    image: eboraas/apache-php
    depends_on: 
        - db        
    restart: always
    volumes: 
        - ./:/var/www/html/
    ports: 
      - "80:80"
      - "443:443"
  